modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"
issueTrackerURL = "https://github.com/VendoAU/MapTooltip/issues"

[[mods]]
modId = "maptooltip"
version = "${file.jarVersion}"
displayName = "Map Tooltip"
logoFile = "assets/maptooltip/icon.png"
authors = "VendoAU"
description = "View maps from your inventory"
displayURL = "https://modrinth.com/mod/map-tooltip"
updateJSONURL = "https://api.modrinth.com/updates/map-tooltip/forge_updates.json"