# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod.version=5.0.0
mod.group=com.venodau.maptooltip
mod.id=maptooltip
mod.name=Map Tooltip
mod.description=View maps from your inventory

# Global dependencies
deps.fabric_loader=0.17.3

publish.modrinth=map-tooltip
publish.curseforge=384852
