# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=4.2
group=com.vendoau.maptooltip
java_version=21

# Common
minecraft_version=1.21.7
mod_name=Map Tooltip
mod_author=VendoAU
mod_id=maptooltip
license=MIT
credits=
description=View maps from your inventory
minecraft_version_range=[1.21, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.7-20250711.194848
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.7
parchment_version=2025.07.18

# Fabric
fabric_version=0.129.0+1.21.7
fabric_loader_version=0.16.13

# NeoForge
neoforge_version=21.7.25-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
