modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/VendoAU/MapTooltip/issues/"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="https://modrinth.com/mod/map-tooltip"
logoFile="assets/maptooltip/icon.png"
authors="VendoAU"
description="${description}"

[[mixins]]
config="${id}.mixins.json"

[[dependencies.${id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge},)"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
ordering="NONE"
side="BOTH"